name: ⚙ Trigger Zotero to Readwise Integration

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *" # Runs every ten minutes every day (for testing) (Check https://crontab.tech/)

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: 🐍 Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: 💿 Install Zotero2Readwise package
        run: pip install zotero2readwise

      - name: 📥 Download Python Script to run the automation
        run:  curl https://raw.githubusercontent.com/e-alizadeh/Zotero2Readwise/master/zotero2readwise/run.py -o run.py

      - name: 🚀 Run the auotmation
        run: python run.py ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}